---
title: "DataFilt_2022.06.23"
author: "Kirstin MacGregor"
date: '2022-06-23'
output: html_document
---

#set up environment
```{r setup}
rm(list= ls())
setwd("C:/Users/kirmac/OneDrive - Karolinska Institutet/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/raw")
library(tidyverse)
library(ggplot2)
library(dplyr)
data <- read.csv("data.full_10.06.21.csv")
```

#compute new MC variables
```{r}
data <- mutate(data, yr_sincelivebirth= (age- X_2764_0_0),
               yr_sincepill= (age- X_2804_0_0),
               yr_sinceHRT= (age- n_3546_0_0),
               MC.status= ((n_3700_0_0/n_3710_0_0)))
Irregular.menstruation <- data %>% filter(n_3700_0_0 > 7 & n_3720_0_0 == "1") 
```

#filter by menstrual cycle characteristics
```{r}
MC.filtered <- data %>% filter(sex== "0", #female
                               age<51,
                               had_menopause == "0", #not undergone menopause
                               is.na(yr_sincelivebirth) | yr_sincelivebirth > 1, #yr since birth >1
                               is.na(X_2824_0_0), #has not had hysterectomy (by default of NA being given to those not asked)
                               is.na(yr_sincepill) | yr_sincepill > 1, #yr since contraceptive pill >1
                               is.na(yr_sinceHRT) | yr_sinceHRT > 1, #yr since HRT >1
                               n_3700_0_0<=36, #time since last period < 36 d
                               between(n_3710_0_0,21,36), #typical menstrual cycle length between 21-36 d
                               between(MC.status, 0, 1), #menstrual cyce status between 0-1
                               Cancer_diagnosed !="1", # had a cancer diagnoses
                               diabetesT2D=="0",
                               n_74_0_0 >=4, # more than 4 hours fasting duration
                               between(n_30800_0_0, 31, 2864)) #estradiol concentration between 31-2864, ref paper- Verdonk et al, 2019.
MC.filtered<- anti_join(MC.filtered, Irregular.menstruation, by = "eid")
```

#compute new metabolic variables
```{r}
MC.filtered <- mutate(MC.filtered, TC.HDL = Tchol_0/HDL_0,
                      GL.mg.dL = n_30740_0_0*18.018,
                      TG.ml.dL = TG_0*88.57)

MC.filtered <- mutate(MC.filtered, tyG.index1= log(GL.mg.dL*TG.ml.dL/2),
                      tyG.index2 = log(GL.mg.dL*TG.ml.dL)/2,
                      MET.summed = n_22037_0_0 + n_22038_0_0 + n_22039_0_0)
```


#compute new covariate variables required for GAM analysis 
```{r}
#Bodyfatp.tertiles
Bodyfatp.tertiles <-  MC.filtered %>%
  mutate(bodyfat_p_new= (bodyfat_kg/weight_kg)*100,
    Bodyfatp.tertiles = ntile(bodyfat_p_new, 4)) %>% select(c('eid', 'Bodyfatp.tertiles'))
MC.filtered <- left_join(MC.filtered, Bodyfatp.tertiles, by="eid")

#muslcle.mass.perc.tertiles
muslcle.mass.perc.tertiles <-  MC.filtered %>%
  mutate(bodyfatfree_p_new= (bodyfatfreemass/weight_kg)*100,
    muslcle.mass.perc.tertiles = ntile(bodyfatfreemass, 4)) %>% select(c('eid', 'muslcle.mass.perc.tertiles'))
MC.filtered <- left_join(MC.filtered, muslcle.mass.perc.tertiles, by="eid")

#handgripkg age specific z score tertiles
#make new column for age group categories
handgripkg.tertiles <-MC.filtered %>% mutate(AgeCat = case_when( 
  between(age,40,42.5)~ "40to42.5",
  between(age,42.50000000000000000001,45.0)~ "42.5to45",
  between(age,45.00000000000000000001,47.5)~ "45to47.5",
  between(age,47.50000000000000000001,50.0)~ "47.5to50",
  TRUE~'O'))
#Calculate mean expression for grip strength per age group
handgripkg.tertiles <- handgripkg.tertiles %>%
  group_by(AgeCat) %>%
  mutate(mean.gripstrength.by.age = mean(handgripkg, na.rm=T),
         sd.gripstrength.by.age = sd(handgripkg, na.rm=T),
         zscore.gripstrength.by.age = (handgripkg- mean.gripstrength.by.age)/sd.gripstrength.by.age) %>% 
  ungroup()
#merge tertiles with full dataset
handgripkg.tertiles <-  handgripkg.tertiles %>%
  mutate(handgripkg.tertiles = ntile(zscore.gripstrength.by.age, 4)) %>% select(c('eid', 'handgripkg.tertiles'))
MC.filtered <- left_join(MC.filtered, handgripkg.tertiles, by="eid")

#Fitness_METs_c age specific z score tertiles
#make new column for age group categories
Fitness_METs_c.tertiles <-MC.filtered %>% mutate(AgeCat = case_when( 
  between(age,40,42.5)~ "40to42.5",
  between(age,42.50000000000000000001,45.0)~ "42.5to45",
  between(age,45.00000000000000000001,47.5)~ "45to47.5",
  between(age,47.50000000000000000001,50.0)~ "47.5to50",
  TRUE~'O'))
#Calculate mean expression for grip strength per age group
Fitness_METs_c.tertiles <- Fitness_METs_c.tertiles %>%
  group_by(AgeCat) %>%
  mutate(mean.fitness_METs.by.age = mean(Fitness_METs_c, na.rm=T),
         sd.fitness_METs.by.age = sd(Fitness_METs_c, na.rm=T),
         zscore.fitness_METs.by.age = (Fitness_METs_c- mean.fitness_METs.by.age)/sd.fitness_METs.by.age) %>% 
  ungroup()
#merge tertiles with full dataset
Fitness_METs_c.tertiles <-  Fitness_METs_c.tertiles %>%
  mutate(Fitness_METs_c.tertiles = ntile(zscore.fitness_METs.by.age, 4)) %>% select(c('eid', 'Fitness_METs_c.tertiles'))
MC.filtered <- left_join(MC.filtered, Fitness_METs_c.tertiles, by="eid")
```


#save new file for downstream analysis
```{r}
write.csv(MC.filtered, 'filtered.data_20220627.csv')
```
