---
title: "Reviewer response: Examining hyperlipidaemia"
author: "Kirstin MacGregor"
date: '2022-06-23'
output: html_document
editor_options: 
  chunk_output_type: console
---

# Set up environment
```{r setup}
rm(list = ls())
```

# Load data

## Load
```{r}
data <- read.csv("C:/Users/kirmac/OneDrive - Karolinska Institutet/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/filtered/filtered.data_20220627.csv")

med_data <- haven::read_dta("C:/Users/kirmac/OneDrive - Karolinska Institutet/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/raw/Data_medication_20230919.dta")
```

## Merge data 
```{r, warning=FALSE}
data <- data |>
  dplyr::left_join(med_data, by = "eid") |>
  dplyr::mutate(
    medicationCV = dplyr::case_when(
      is.na(medicationCV) ~ "none",
      TRUE ~ paste(medicationCV),
    ),
    CVmeds = factor(CVmeds),
    statin = factor(statin)
  )
```

# Lipid profiles

## Check distribution
```{r, warning=FALSE}
hist_fun <- function(x_var, x_int, title){
ggplot2::ggplot() +
  ggplot2::geom_histogram(ggplot2::aes(x_var))+
  ggplot2::geom_vline(xintercept = x_int)+
  ggplot2::ggtitle(title)+
  ggplot2::theme_bw()
}

LDL_hist <- hist_fun(x_var =as.numeric(data$ldl_0), x_int = c(2.586, 4.1376), title = "LDL (mmol/L)")
TG_hist <- hist_fun(x_var =as.numeric(data$TG_0), x_int = c(1.693576, 2.258101), title = "Triglyceride (mmol/L)")
TC_hist <- hist_fun(x_var =as.numeric(data$Tchol_0), x_int = c(5.172, 6.2064), title = "Total cholesterol (mmol/l)")
```

# N and % in each category
```{r, message=FALSE, warning=FALSE}
TG_n_per_cat <- data |>
    dplyr::filter(TG_0 != "NA") |> 
  dplyr::mutate(cat = dplyr::case_when(
    TG_0 < 1.693576 ~ "low",
    TG_0 < 2.25811 ~ "med",
    TG_0 > 2.258101 ~ "high"
  )) |> 
  dplyr:: count(cat) |> 
  dplyr::mutate(var = "Triglyceride",
                total = 8653)

LDL_n_per_cat <- data |>
    dplyr::filter(ldl_0 != "NA") |> 
  dplyr::mutate(cat = dplyr::case_when(
    ldl_0 < 2.586 ~ "low",
    ldl_0 < 4.1376 ~ "med",
    ldl_0 > 4.1376 ~ "high"
  )) |> 
  dplyr:: count(cat)|> 
  dplyr::mutate(var = "LDL",
                total = 8638)

TChol_n_per_cat <- data |>
  dplyr::filter(Tchol_0 != "NA") |> 
  dplyr::mutate(cat = dplyr::case_when(
    Tchol_0 < 5.172 ~ "low",
    Tchol_0 < 6.2064 ~ "med",
    Tchol_0 > 6.2064 ~ "high"
  )) |> 
  dplyr:: count(cat)|> 
  dplyr::mutate(var = "Total cholesterol",
                total = 8651)

all <- rbind(TG_n_per_cat, LDL_n_per_cat, TChol_n_per_cat) |> 
  dplyr::mutate(perc = (n/total)*100,
                cat = factor(cat, levels = c("low", "med", "high")))

lipid_characteristics_bar <-ggplot2::ggplot(data = all, ggplot2::aes(x= var, y = perc, group = cat, fill = cat)) +
  ggplot2::geom_bar(position="dodge", stat="identity")+
  viridis::scale_fill_viridis(discrete = T)+
  ggplot2::geom_text(position = ggplot2::position_dodge(width= 0.9), ggplot2::aes(label=paste(round(perc, 0), " %", sep=""), hjust=0.5, vjust = -1))+
  ggplot2::ylim(c(0,100))+
  ggplot2::theme_bw()
```

## Plots 
* Lines on histgram refer to medium and high risk concentrations of each metabolite
```{r, message = FALSE, warning=FALSE}
ggpubr::ggarrange(TG_hist, LDL_hist, TC_hist)
lipid_characteristics_bar
```

# Medication usage

## N and % in each category
```{r, message=FALSE, warnings = F}
# CVD medication
med_count_plot <- ggplot2::ggplot(data = data, ggplot2::aes(medicationCV)) +
  ggplot2::geom_bar() +
  ggplot2::ggtitle("#6177: Medication for cholesterol, blood pressure or diabetes") +
  ggplot2::ylab("count (n)") +
  ggplot2::theme_bw() +
  ggplot2::geom_text(stat = "count", ggplot2::aes(label = ggplot2::after_stat(count)), vjust = 0)

med_perc_plot <- ggplot2::ggplot(
  data = data |>
    dplyr::group_by(medicationCV) |>
    dplyr::summarise(n = dplyr::n()) |>
    dplyr::mutate(perc = 100 * (n / sum(n))),
  ggplot2::aes(x = medicationCV, y = perc)
) +
  ggplot2::geom_col()  +
  ggplot2::ggtitle("#6177: Medication for 
cholesterol, blood 
pressure or diabetes") +
  ggplot2::ylab("count (%)") +
  ggplot2::theme_bw() +
    ggplot2::ylim(c(0,110))+
  ggplot2::geom_text(ggplot2::aes(label = paste(round(perc, 1), " %")), vjust = -0.5)

# Statins
statin_count_plot <- ggplot2::ggplot(data = data, ggplot2::aes(statin)) +
  ggplot2::geom_bar() +
  ggplot2:::ggtitle("Statin") +
  ggplot2::ylab("count (%)") +
  ggplot2::theme_bw() +
  ggplot2::geom_text(stat = "count", ggplot2::aes(label = ggplot2::after_stat(count)), vjust = 0)

statin_perc_plot <-
  ggplot2::ggplot(
    data = data |>
      dplyr::group_by(statin) |>
      dplyr::summarise(n = dplyr::n()) |>
      dplyr::mutate(perc = 100 * (n / sum(n))),
    ggplot2::aes(x = statin, y = perc)
  ) +
  ggplot2::geom_col() +
  ggplot2:::ggtitle("Statin
                    
                    ") +
    ggplot2::ylim(c(0,110))+
  ggplot2::ylab("count (%)") +
  ggplot2::theme_bw() +
  ggplot2::geom_text(ggplot2::aes(label = paste(round(perc, 1), " %")), vjust = -0.5)

# CV meds
CVmeds_count_plot <- ggplot2::ggplot(data = data, ggplot2::aes(CVmeds)) +
  ggplot2::geom_bar() +
  ggplot2:::ggtitle("Cardiovascular disease medication") +
  ggplot2::ylab("count (%)") +
  ggplot2::theme_bw() +
  ggplot2::geom_text(stat = "count", ggplot2::aes(label = ggplot2::after_stat(count)), vjust = 0)

CVmeds_perc_plot <- ggplot2::ggplot(
  data = data |>
    dplyr::group_by(CVmeds) |>
    dplyr::summarise(n = dplyr::n()) |>
    dplyr::mutate(perc = 100 * (n / sum(n))),
  ggplot2::aes(x = CVmeds, y = perc)
) +
  ggplot2::geom_col()+
  ggplot2:::ggtitle("Cardiovascular disease 
medication
") + 
  ggplot2::ylim(c(0,110))+
  ggplot2::ylab("count (%)") +
  ggplot2::theme_bw() +
  ggplot2::geom_text(ggplot2::aes(label = paste(round(perc, 1), " %")), vjust = -0.5)
```

## Plots out 
```{r}
ggpubr::ggarrange(med_count_plot, statin_count_plot, CVmeds_count_plot, ncol=3)
ggpubr::ggarrange(med_perc_plot, statin_perc_plot, CVmeds_perc_plot, ncol = 3)
```

# Session info
```{r}
sessionInfo()
```



