---
title: "metab ~ potential mediator"
author: "Kirstin MacGregor"
date: '2022-08-26'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(lme4)
library(mgcv)
library(tidymv)
rm(list= ls())
```

#set up data and arange
```{r}
setwd("P:/C3_Integrative_Physiology_Group/PeoplesData/Kirstin/Projects/UoS/MC and metabolites_BioBank/Data")
data <- read.csv("filtered.data_20220627.csv")

data <- data %>% transform(ethnicity_cat= as.factor(ethnicity_cat),
                           age= as.numeric(age),
                           n_22038_0_0= as.numeric(n_22038_0_0),
                           n_22039_0_0= as.numeric(n_22039_0_0),
                           n_22037_0_0= as.numeric(n_22037_0_0),
                           MET.summed= as.numeric(MET.summed))
```

#variables for loop
```{r}
variables_loop<- c('n_30740_0_0', 'Tchol_0', 'TG_0', 'ldl_0', 'HDL_0', 'TC.HDL', 'tyG.index2')
```


#inflamatory markers
```{r}
mod_out <- data.frame(matrix(ncol =23, nrow = 0))
inflam_loop <- c('CRP_0', 'n_30800_0_0')

for (i in variables_loop) {
  
  data_loop <- rename(data, var= i)
  
  for (j in inflam_loop){
    
  data_loop <- rename(data_loop, covar= j)  
  
  mod1 <- gam(var~  ethnicity_cat + s(MC.status, bs="cc") + s(age) + s(deprivationindex) + s(covar), data=data_loop)
  summary <- summary(mod1) #summary of model
  s.summary <- as_tibble(summary$s.table)
  nval.summary <- as_tibble(summary$n)
  dev.summary <- as_tibble(summary$dev.expl)
  MC.summary <- s.summary[1,]
  full.summary <- cbind(nval.summary, dev.summary, MC.summary)
  colnames(full.summary) <- c( 'N val', 'Dev exp', 'MC.EDF', 'MC.Ref.df', 'MC.F', 'MC.pval')
  full.summary <- full.summary %>% dplyr::mutate(Variable= paste(i), inflam=paste(j))
  
  a <- plot_smooths(model= mod1, series= MC.status)
  plot.data <- a[['data']]
  plot.data <- plot.data %>% filter(ethnicity_cat== 1)
  max.val <- max(plot.data$var)
  min.val <- min(plot.data$var)
  plot.data.max <- plot.data %>% filter(var == max.val) %>% distinct(var, .keep_all= TRUE)
  plot.data.min <- plot.data %>% filter(var == min.val) %>% distinct(var, .keep_all= TRUE)
  plot.data <- cbind(plot.data.min, plot.data.max)
  colnames(plot.data) <- c( 'idx', 'ethnicity', 'min.MC.status', 'min.outcomevar', 'min.SE', 'min.CI_upper', 'min.CI_lower',
                            'idx', 'ethnicity', 'max.MC.status', 'max.outcomevar', 'max.SE', 'max.CI_upper', 'max.CI_upper')
  out<- cbind(full.summary, plot.data)
  
mod_out <- rbind(mod_out, out) }  }


#getwd()
#write.csv(mod_out, 'inflamCovarAdj_MC_metab.csv')

```