---
title: "MC ~ potential mediator"
author: "Kirstin MacGregor"
date: '2022-08-26'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(lme4)
library(mgcv)
library(tidymv)
library(viridis)
library(ggpubr)
rm(list= ls())
```

#set up data and arange
```{r}
data <- read.csv("P:/C3_Integrative_Physiology_Group/PeoplesData/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/filtered/filtered.data_20220627.csv")


data <- data %>% transform(ethnicity_cat= as.factor(ethnicity_cat),
                           age= as.numeric(age),
                           n_22038_0_0= as.numeric(n_22038_0_0),
                           n_22039_0_0= as.numeric(n_22039_0_0),
                           n_22037_0_0= as.numeric(n_22037_0_0),
                           MET.summed= as.numeric(MET.summed))
```

#variables for loop
```{r}
mediators_loop <- c('CRP_0', 'n_30800_0_0', 'bmi', 'bodyfat_p', 'SMusclemasspct_c', 'MET.summed', 'handgripkg', 'Fitness_METs_c')
mediators_loop <- c('CRP_0', 'n_30800_0_0', 'bmi', 'bodyfat_p', 'SMusclemasspct_c', 'MET.summed', 'handgripkg', 'Fitness_METs_c')
```


# Simple model
```{r}
mod_out_simple <- data.frame(matrix(ncol =22, nrow = 0))

for (i in mediators_loop) {
  data_loop <- rename(data, var= i)
  
  mod1 <- gam(var~  s(MC.status, bs="cc") + ethnicity_cat + s(age) + s(deprivationindex), data=data_loop)
  summary <- summary(mod1) #summary of model
  s.summary <- as_tibble(summary$s.table)
  nval.summary <- as_tibble(summary$n)
  dev.summary <- as_tibble(summary$dev.expl)
  MC.summary <- s.summary[1,]
  full.summary <- cbind(nval.summary, dev.summary, MC.summary)
  colnames(full.summary) <- c( 'N val', 'Dev exp', 'MC.EDF', 'MC.Ref.df', 'MC.F', 'MC.pval')
  full.summary <- full.summary %>% dplyr::mutate(Variable= paste(i))
  
  a <- plot_smooths(model= mod1, series= MC.status)
  plot.data <- a[['data']]
  plot.data <- plot.data %>% filter(ethnicity_cat== 1)
  plot.data <- mutate(plot.data, mediator= paste(i))
  assign(paste('plot.data_', i, sep=''), plot.data)
  max.val <- max(plot.data$var)
  min.val <- min(plot.data$var)
  plot.data.max <- plot.data %>% filter(var == max.val) %>% distinct(var, .keep_all= TRUE)
  plot.data.min <- plot.data %>% filter(var == min.val) %>% distinct(var, .keep_all= TRUE)
  plot.data <- cbind(plot.data.min, plot.data.max)
  colnames(plot.data) <- c( 'idx', 'ethnicity', 'min.MC.status', 'min.outcomevar', 'min.SE', 'min.CI_upper', 'min.CI_lower',
                            'idx', 'ethnicity', 'max.MC.status', 'max.outcomevar', 'max.SE', 'max.CI_upper', 'max.CI_upper')
  out<- cbind(full.summary, plot.data)
  
  mod_out <- rbind(mod_out_simple, out) 
  
  rm(data_loop, mod1, summary, s.summary, nval.summary, dev.summary, MC.summary, full.summary, a, plot.data, max.val, min.val, 
     plot.data.max, plot.data.min, out) }

write.csv(mod_out_simple,
          'P:/C3_Integrative_Physiology_Group/PeoplesData/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/out/Potential mediator/ metab~mediator_simple.csv')
```


#2. Fasting duration adjusted
```{r}
mod_out_fasted <- data.frame(matrix(ncol =22, nrow = 0))

for (i in mediators_loop) {
  data_loop <- rename(data, mediator= i)

  mod1 <- gam(var~  s(MC.status, bs="cc") + ethnicity_cat + s(age) + s(deprivationindex), data=data_loop)
  summary <- summary(mod1) #summary of model
  s.summary <- as_tibble(summary$s.table)
  nval.summary <- as_tibble(summary$n)
  dev.summary <- as_tibble(summary$dev.expl)
  MC.summary <- s.summary[1,]
  full.summary <- cbind(nval.summary, dev.summary, MC.summary)
  colnames(full.summary) <- c( 'N val', 'Dev exp', 'MC.EDF', 'MC.Ref.df', 'MC.F', 'MC.pval')
  full.summary <- full.summary %>% dplyr::mutate(Variable= paste(i))
  
  a <- plot_smooths(model= mod1, series= MC.status)
  plot.data <- a[['data']]
  plot.data <- plot.data %>% filter(ethnicity_cat== 1)
  max.val <- max(plot.data$var)
  min.val <- min(plot.data$var)
  plot.data.max <- plot.data %>% filter(var == max.val) %>% distinct(var, .keep_all= TRUE)
  plot.data.min <- plot.data %>% filter(var == min.val) %>% distinct(var, .keep_all= TRUE)
  plot.data <- cbind(plot.data.min, plot.data.max)
  colnames(plot.data) <- c( 'idx', 'ethnicity', 'min.MC.status', 'min.outcomevar', 'min.SE', 'min.CI_upper', 'min.CI_lower',
                            'idx', 'ethnicity', 'max.MC.status', 'max.outcomevar', 'max.SE', 'max.CI_upper', 'max.CI_upper')
  out<- cbind(full.summary, plot.data)
  
  mod_out_fasted <- rbind(mod_out_fasted, out) 
  
  rm(data_loop, mod1, summary, s.summary, nval.summary, dev.summary, MC.summary, full.summary, a, plot.data, max.val, min.val, 
     plot.data.max, plot.data.min, out) }

write.csv(mod_out_fasted,
          'P:/C3_Integrative_Physiology_Group/PeoplesData/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/out/Potential mediator/metab~mediator_fastedDur.csv')
```


#3. excluding women with menstrual cycle symptoms
```{r}
data.n_21050_0_0 <- data %>% filter(n_21050_0_0 == "-601" | n_21050_0_0 == "-602")
data.n_21026_0_0 <- data %>% filter(n_21026_0_0 == "1")
Data.MCsymptoms <- rbind(data.n_21050_0_0, data.n_21026_0_0)
data_MC <- anti_join(data, Data.MCsymptoms, by = 'eid')

mod_out_MCsymptoms <- data.frame(matrix(ncol =22, nrow = 0))

for (i in mediators_loop) {
  data_loop <- rename(data, var= i)
  
  mod1 <- gam(var~  s(MC.status, bs="cc") + ethnicity_cat + s(age) + s(deprivationindex), data=data_loop)
  summary <- summary(mod1) #summary of model
  s.summary <- as_tibble(summary$s.table)
  nval.summary <- as_tibble(summary$n)
  dev.summary <- as_tibble(summary$dev.expl)
  MC.summary <- s.summary[1,]
  full.summary <- cbind(nval.summary, dev.summary, MC.summary)
  colnames(full.summary) <- c( 'N val', 'Dev exp', 'MC.EDF', 'MC.Ref.df', 'MC.F', 'MC.pval')
  full.summary <- full.summary %>% dplyr::mutate(Variable= paste(i))
  
  a <- plot_smooths(model= mod1, series= MC.status)
  plot.data <- a[['data']]
  plot.data <- plot.data %>% filter(ethnicity_cat== 1)
  max.val <- max(plot.data$var)
  min.val <- min(plot.data$var)
  plot.data.max <- plot.data %>% filter(var == max.val) %>% distinct(var, .keep_all= TRUE)
  plot.data.min <- plot.data %>% filter(var == min.val) %>% distinct(var, .keep_all= TRUE)
  plot.data <- cbind(plot.data.min, plot.data.max)
  colnames(plot.data) <- c( 'idx', 'ethnicity', 'min.MC.status', 'min.outcomevar', 'min.SE', 'min.CI_upper', 'min.CI_lower',
                            'idx', 'ethnicity', 'max.MC.status', 'max.outcomevar', 'max.SE', 'max.CI_upper', 'max.CI_upper')
  out<- cbind(full.summary, plot.data)
  
  mod_out_MCsymptoms <- rbind(mod_out_MCsymptoms, out)

  rm(data_loop, mod1, summary, s.summary, nval.summary, dev.summary, MC.summary, full.summary, a, plot.data, max.val, min.val, 
     plot.data.max, plot.data.min, out) } 

write.csv(mod_out_MCsymptoms,
          'P:/C3_Integrative_Physiology_Group/PeoplesData/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/out/Potential mediator/metab~mediator_MCexcluded.csv')
```


```{r}

plot.data.pChars <- rbind(plot.data_bmi, plot.data_bodyfat_p, plot.data_SMusclemasspct_c, plot.data_MET.summed, plot.data_Fitness_METs_c,
                          plot.data_handgripkg)
plot.data.pChars <- plot.data.pChars %>%  mutate(mediator = replace(mediator, mediator=="bmi", "BMI (kg/m2)"),
                                            mediator = replace(mediator, mediator=="bodyfat_p", "Fat mass (%)"),
                                            mediator = replace(mediator, mediator=="SMusclemasspct_c", "Fat free mass (%)"),
                                            mediator = replace(mediator, mediator=="MET.summed", "Summed physical activity (MET min/ wk)"),
                                            mediator = replace(mediator, mediator=="Fitness_METs_c", "Cardiorespiratory fitness (METs)"),
                                            mediator = replace(mediator, mediator=="handgripkg", "Handgrip strength (kg)"))

plot.dat.metabolites$Variable <- factor(plot.dat.metabolites$Variable, levels= c("BMI (kg/m2)", "Fat mass (%)", "Fat free mass (%)",
                                                                                 "Summed physical activity (MET min/ wk)", "Cardiorespiratory fitness (METs)",
                                                                                 "Handgrip strength (kg)"))

plot.data.inflam <- rbind(plot.data_CRP_0, plot.data_n_30800_0_0)
plot.data.inflam <- plot.data.inflam %>%  mutate(mediator = replace(mediator, mediator=="CRP_0", "CRP (mg/L)"),
                                                 mediator = replace(mediator, mediator=="n_30800_0_0", "IGF-1 (mmol/L)"))                  

plot.pChars <- ggplot(data =plot.data.pChars)+
  geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill= "#39568CFF"),alpha = 0.5)+
  scale_fill_manual(values = c("#39568CFF"))+
  geom_line(aes(y=var, x=MC.status))+
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x =element_blank(),
        legend.position = 'none')+
  facet_wrap(~ mediator,scales= 'free', ncol=2)

plot.inflam <- ggplot(data =plot.data.inflam)+
  geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill= "#39568CFF"),alpha = 0.5)+
  scale_fill_manual(values = c("#39568CFF"))+
  geom_line(aes(y=var, x=MC.status))+
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x =element_blank(),
        legend.position = 'none')+
  facet_wrap(~ mediator,scales= 'free', ncol=2, nrow=3)



plot.pChars #save at  6 x 8
plot.inflam #save at  3 x 6
```
