---
title: "MC ~ metabolite + subgroup analysis"
author: "Kirstin MacGregor"
date: '2022-08-26'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(lme4)
library(mgcv)
library(tidymv)
library(viridis)
library(ggpubr)
rm(list= ls())
```

#set up data and arange
```{r}
setwd("P:/C3_Integrative_Physiology_Group/PeoplesData/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/filtered")
data <- read.csv("filtered.data_20220627.csv")

#sort out IPAQ cat labels so they are 1,2,3 not 0,1,2
data <- data %>% mutate(n_22032_0_0 = case_when(
  n_22032_0_0 == 0 ~ 1,
  n_22032_0_0 == 1 ~ 2,
  n_22032_0_0 == 2 ~ 3))

data <- data %>% transform(Fitness_METs_c.tertiles=as.factor(Fitness_METs_c.tertiles),
                           muslcle.mass.perc.tertiles= as.factor(muslcle.mass.perc.tertiles),
                           Bodyfatp.tertiles= as.factor(Bodyfatp.tertiles),
                           handgripkg.tertiles= as.factor(handgripkg.tertiles),
                           n_22032_0_0 = as.factor(n_22032_0_0), 
                           deprivationindex= as.numeric(deprivationindex),
                           ethnicity_cat= as.factor(ethnicity_cat),
                           age= as.numeric(age))



```

#variables for loop
```{r}
metabolite_loop <- c('n_30740_0_0', 'Tchol_0', 'TG_0', 'ldl_0', 'HDL_0', 'TC.HDL', 'tyG.index2')

subgroup_loop <- c('handgripkg.tertiles', 'Fitness_METs_c.tertiles', 'Bodyfatp.tertiles', 'muslcle.mass.perc.tertiles')
cats_4 <- c('1', '2', '3', '4')
IPAQ<- 'n_22032_0_0' #only 3 categories so will have to be done separately.
cats_3 <- c('1', '2', '3')
```


#simple model
```{r}
mod_out_subgroup <- data.frame(matrix(ncol =22, nrow = 0))
interaction_loop <- list()
interaction_names <- c()
plot.data.all <- data.frame(matrix(ncol =9, nrow = 0))

#for all sub-groups except from IPAQ
for (i in metabolite_loop) {
  data_loop <- rename(data, var= i)
  
  for (j in subgroup_loop) {
    data_loop_2 <- rename(data_loop, subgroupVar=j)
    mod1 <- gam(var~ subgroupVar + s(MC.status, by=subgroupVar, bs="cc") + ethnicity_cat + s(age)+ s(deprivationindex), data=data_loop_2)
    summary <- summary(mod1) #summary of model
    s.summary <- as_tibble(summary$s.table)
    nval.summary <- as_tibble(summary$n)
    dev.summary <- as_tibble(summary$dev.expl)
    MC.summary <- s.summary[1:4,]
    MC.summary <- MC.summary[1:4,]
    full.summary <- cbind(nval.summary, dev.summary, MC.summary)
    colnames(full.summary) <- c( 'N val', 'Dev exp', 'MC.EDF', 'MC.Ref.df', 'MC.F', 'MC.pval')
    full.summary <- full.summary %>% mutate(Variable= paste(i), subgroup= paste(j), Level = c(1,2,3,4))
    
    #set up simple model with same number of observations (required for comparing models with ´anova´) and save into list with subgroup model for later
    dat_loop_comp <- data_loop_2 %>% drop_na(subgroupVar)
    mod.simple <- gam(var~ ethnicity_cat + s(MC.status, bs="cc") + s(age) + s(deprivationindex), data=dat_loop_comp) 
    temp_loop <- list(temp = list("mod1" = mod1, "mod2" = mod.simple, "var" = i, "subGroup" = j))
    names(temp_loop)[1] <- paste(i, j, sep='_')
    interaction_loop<- append(interaction_loop, temp_loop)
    interaction_names <- append(interaction_names, paste(i, j, sep='_'))
    
    for (n in cats_4) {
      plot.data_out_simple <- data.frame(matrix(ncol =16, nrow = 0))
      a <- plot_smooths(model=mod1,series=MC.status)
      plot.data <- a[['data']]
      plot.data <- plot.data %>% filter(ethnicity_cat== 1)
      plot.data2 <- plot.data %>%  mutate(Variable= paste(i), Subgroup= paste(j))
      plot.data <- plot.data %>% select(-c('.idx', 'ethnicity_cat', 'SE'))
      cat <- plot.data %>% filter(subgroupVar==n)
      max.val <- max(cat$var)
      min.val <- min(cat$var)
      plot.data.min <- cat %>% filter(var == min.val) %>% distinct(var, .keep_all= TRUE)
      plot.data.max <- cat %>% filter(var == max.val) %>% distinct(var, .keep_all= TRUE)
      plot.data.cat <- cbind(plot.data.min, plot.data.max)
      colnames(plot.data.cat) <- c('min.subgroupVar ', 'min.MC.status', 'min.outcomevar', 'min.CI_upper', 'min.CI_lower',
                                   'max.subgroupVar', 'max.MC.status', 'max.outcomevar', 'max.CI_upper', 'max.CI_lower')
      plot.data_out_simple <- rbind(plot.data_out_simple, plot.data.cat) 
      rm(cat, min.val, max.val, plot.data.min, plot.data.cat, a)  }
    plot.data.all <- rbind(plot.data.all, plot.data2)
    out <-cbind(full.summary, plot.data_out_simple)
    mod_out_subgroup <- rbind(mod_out_subgroup, out)
    
    rm(mod1, summary, s.summary, nval.summary, MC.summary, full.summary, plot.data, plot.data_out_simple, dat_loop_comp, data_loop_2, out, plot.data.max,
       temp_loop, mod.simple, dev.summary) } }

#for IPAQ
for (i in metabolite_loop) {
  data_loop <- rename(data, var= i)
  
  for (j in IPAQ) {
    data_loop_2 <- rename(data_loop, subgroupVar=j)
    mod1 <- gam(var~ subgroupVar + s(MC.status, by=subgroupVar, bs="cc") + ethnicity_cat + s(age)+ s(deprivationindex), data=data_loop_2)
    summary <- summary(mod1) #summary of model
    s.summary <- as_tibble(summary$s.table)
    nval.summary <- as_tibble(summary$n)
    dev.summary <- as_tibble(summary$dev.expl)
    MC.summary <- s.summary[1:3,]
    MC.summary <- MC.summary[1:3,]
    full.summary <- cbind(nval.summary, dev.summary, MC.summary)
    colnames(full.summary) <- c( 'N val', 'Dev exp', 'MC.EDF', 'MC.Ref.df', 'MC.F', 'MC.pval')
    full.summary <- full.summary %>% mutate(Variable= paste(i), subgroup= paste(j), Level = c(1,2,3))
    
    #set up simple model with same number of observations (required for comparing models with ´anova´) and save into list with subgroup model for later
    dat_loop_comp <- data_loop_2 %>% drop_na(subgroupVar)
    mod.simple <- gam(var~ ethnicity_cat + s(MC.status, bs="cc") + s(age) + s(deprivationindex), data=dat_loop_comp) 
    temp_loop <- list(temp = list("mod1" = mod1, "mod2" = mod.simple, "var" = i, "subGroup" = j))
    names(temp_loop)[1] <- paste(i, j, sep='_')
    interaction_loop<- append(interaction_loop, temp_loop)
    interaction_names <- append(interaction_names, paste(i, j, sep='_'))
    
    for (n in cats_3) {
      plot.data_out_simple <- data.frame(matrix(ncol =16, nrow = 0))
      a <- plot_smooths(model=mod1,series=MC.status)
      plot.data <- a[['data']]
      plot.data <- plot.data %>% filter(ethnicity_cat== 1)
      plot.data2 <- plot.data %>%  mutate(Variable= paste(i), Subgroup= paste(j))
      plot.data <- plot.data %>% select(-c('.idx', 'ethnicity_cat', 'SE'))
      cat <- plot.data %>% filter(subgroupVar==n)
      max.val <- max(cat$var)
      min.val <- min(cat$var)
      plot.data.min <- cat %>% filter(var == min.val) %>% distinct(var, .keep_all= TRUE)
      plot.data.max <- cat %>% filter(var == max.val) %>% distinct(var, .keep_all= TRUE)
      plot.data.cat <- cbind(plot.data.min, plot.data.max)
      colnames(plot.data.cat) <- c('min.subgroupVar ', 'min.MC.status', 'min.outcomevar', 'min.CI_upper', 'min.CI_lower',
                                   'max.subgroupVar', 'max.MC.status', 'max.outcomevar', 'max.CI_upper', 'max.CI_lower')
      plot.data_out_simple <- rbind(plot.data_out_simple, plot.data.cat) 
      rm(cat, min.val, max.val, plot.data.min, plot.data.cat, a) }
    plot.data.all <- rbind(plot.data.all, plot.data2)
    
    out <-cbind(full.summary, plot.data_out_simple)
    mod_out_subgroup <- rbind(mod_out_subgroup, out)

    rm(mod1, summary, s.summary, nval.summary, MC.summary, full.summary, plot.data, plot.data_out_simple, dat_loop_comp, data_loop_2, out, plot.data.max,
       temp_loop, mod.simple, dev.summary, plot.data2) } }

#interaction testing
interaction_fun <- function(x) { anova(x$mod1, x$mod2, test='F') }

interaction_out <- lapply(interaction_loop, interaction_fun)

#unlist interaction test output
interaction_dat_out <- setNames(data.frame(matrix(ncol =4, nrow = 0)), c('Fval', 'Pval', 'condition'))

for (i in interaction_names) {
  temp <- interaction_out[[i]]
  F <- temp$F
  pval <- temp$`Pr(>F)`
  out <- cbind(F, pval)
  out <- out[2,]
  out <- out %>% as.data.frame() %>% t()
  out <- out %>% as.data.frame() %>% mutate(Condition = paste(i)) %>% rename(interaction.F= F, interaction.pValue = pval)
  interaction_dat_out <- rbind(interaction_dat_out, out)
  rm(out, temp, pval, F) } 


#merge subgroup with interaction data
mod_out_subgroup <- mod_out_subgroup %>% mutate(Condition= paste(Variable, subgroup, sep='_')) %>% 
  left_join(interaction_dat_out, by= 'Condition') %>%
  select(-c('Condition'))


rm(interaction_loop, interaction_out, interaction_dat_out, data_loop)

write.csv(mod_out_subgroup, 
          'P:/C3_Integrative_Physiology_Group/PeoplesData/Kirstin/Projects/UoS/MC and metabolites_BioBank/Analysis/data/out/Rhythmicity analysis/Moderator/MC~metab+moderator_simple.csv')
```


#plots

#check this- it is a copy paste from old .rmd
``` {r}
plot.data.all <- plot.data.all %>%  mutate(Variable = replace(Variable, Variable=="n_30740_0_0", "Glucose"),
                                       Variable = replace(Variable, Variable=="Tchol_0", "TotalCholesterol"),
                                       Variable = replace(Variable, Variable=="TG_0", "Triglyceride"),
                                       Variable = replace(Variable, Variable=="ldl_0", "LDL"),
                                       Variable = replace(Variable, Variable=="HDL_0", "HDL"),
                                       Variable = replace(Variable, Variable=="TC.HDL", "Total.HDLCholesterol"),
                                       Variable = replace(Variable, Variable=="tyG.index2", "TyG"),
                                       Subgroup = replace(Subgroup, Subgroup== 'handgripkg.tertiles', 'Grip strength'),
                                       Subgroup = replace(Subgroup, Subgroup== 'Fitness_METs_c.tertiles', 'Cardiorespiratory fitness'),
                                       Subgroup = replace(Subgroup, Subgroup== 'Bodyfatp.tertiles', 'Fat mass'),
                                       Subgroup = replace(Subgroup, Subgroup== 'muslcle.mass.perc.tertiles', 'Fat-free mass'),
                                       Subgroup = replace(Subgroup, Subgroup== 'n_22032_0_0', 'Physical activity'))

metabolite_loop <- c("Glucose", "TotalCholesterol", "Triglcyeride", "LDL", "HDL", "Total.HDLCholesterol", "TyG")


#sort out the factor level orders
plot.data.all$Subgroup <- factor(plot.data.all$Subgroup, levels =c('Fat mass', 'Fat-free mass','Grip strength', 'Cardiorespiratory fitness', 'Physical activity'))

for (i in metabolite_loop) {
  plot.dat.temp <- plot.data.all %>%  filter(Variable == i)
  assign(paste('plot.dat', i, sep='_'), plot.dat.temp)
  rm(plot.dat.temp) }


Glucose_plot <- ggplot(data=plot.dat_Glucose)+
        geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill=subgroupVar), alpha = 0.5)+
        geom_line(aes(y=var, x=MC.status, linetype=subgroupVar))+
        scale_fill_manual(values = c("#440154FF", "#39568CFF", "#55C667FF", "#DCE319FF"))+
        scale_linetype_manual(values=c("solid", "dotted", "longdash", "dotdash"))+
        labs(y = "Glucose (mmol/L)", x= "Menstrual cycle status") + 
        ylim(4.6,5.3)+
        facet_wrap(~Subgroup, ncol=7)+
        theme(axis.line = element_line(colour = "black"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.title.x =element_blank())

Triglyceride_plot <- ggplot(data=plot.dat_Triglcyeride)+
        geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill=subgroupVar ), alpha = 0.5)+
        geom_line(aes(y=var, x=MC.status, linetype=subgroupVar))+
        scale_fill_manual(values = c("#440154FF", "#39568CFF", "#55C667FF", "#DCE319FF"))+
        scale_linetype_manual(values=c("solid", "dotted", "longdash", "dotdash"))+
        labs(y = "Triglyceride (mmol/L)", x= "Menstrual cycle status") + 
        ylim(0.8,1.8)+
        facet_wrap(~Subgroup, ncol=7)+
        theme(axis.line = element_line(colour = "black"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_blank(),
              axis.title.x =element_blank())

TyG_plot <- ggplot(data=plot.dat_TyG)+
        geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill=subgroupVar ), alpha = 0.5)+
        geom_line(aes(y=var, x=MC.status, linetype=subgroupVar))+
        scale_fill_manual(values = c("#440154FF", "#39568CFF", "#55C667FF", "#DCE319FF"))+
        scale_linetype_manual(values=c("solid", "dotted", "longdash", "dotdash"))+
        labs(y = "TyG index (mmol/L)",  x= "Menstrual cycle status") + 
        ylim(4.2,4.8)+
        facet_wrap(~Subgroup, ncol=7)+
        theme(axis.line = element_line(colour = "black"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_blank(),
              axis.title.x =element_blank())

plot <- ggplot(data=plot.dat)+
        geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill=Category ), alpha = 0.5)+
        geom_line(aes(y=var, x=MC.status, linetype=Category))+
        scale_fill_manual(values = c("#440154FF", "#39568CFF", "#55C667FF", "#DCE319FF"))+
        scale_linetype_manual(values=c("solid", "dotted", "longdash", "dotdash"))+
        labs(y = "Total cholesterol (mmol/L)",  x= "Menstrual cycle status") + 
        ylim(4.9,5.9)+
        facet_rep_wrap(~Covariate, ncol=7, scales="free")+
        theme(axis.line = element_line(colour = "black"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.title.x =element_blank())
TC.plot <- plot

plot <- ggplot(data=plot.dat)+
        geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill=Category ), alpha = 0.5)+
        geom_line(aes(y=var, x=MC.status, linetype=Category))+
        scale_fill_manual(values = c("#440154FF", "#39568CFF", "#55C667FF", "#DCE319FF"))+
        scale_linetype_manual(values=c("solid", "dotted", "longdash", "dotdash"))+
        labs(y = "HDL (mmol/L)", x= "Menstrual cycle status") + 
        ylim(1.2,1.9)+
        facet_rep_wrap(~Covariate, ncol=7, scales="free")+
        theme(axis.line = element_line(colour = "black"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_blank(),
              axis.title.x =element_blank())
HDL.plot <- plot

plot <- ggplot(data=plot.dat)+
        geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill=Category ), alpha = 0.5)+
        geom_line(aes(y=var, x=MC.status, linetype=Category))+
        scale_fill_manual(values = c("#440154FF", "#39568CFF", "#55C667FF", "#DCE319FF"))+
        scale_linetype_manual(values=c("solid", "dotted", "longdash", "dotdash"))+
        labs(y = "LDL (mmol/L)", x= "Menstrual cycle status") + 
        ylim(2.9,3.7)+
        facet_rep_wrap(~Covariate, ncol=7, scales="free")+
        theme(axis.line = element_line(colour = "black"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_blank(),
              axis.title.x =element_blank())

plot <- ggplot(data=plot.dat)+
        geom_ribbon(aes(x=MC.status, ymin = CI_lower, ymax = CI_upper, fill=Category ), alpha = 0.5)+
        geom_line(aes(y=var, x=MC.status, linetype=Category))+
        scale_fill_manual(values = c("#440154FF", "#39568CFF", "#55C667FF", "#DCE319FF"))+
        scale_linetype_manual(values=c("solid", "dotted", "longdash", "dotdash"))+
        labs(y = "Total cholesterol:HDL (mmol/L)",
             x= "Menstrual cycle status") + 
        ylim(3,4.5)+
        facet_rep_wrap(~Covariate, ncol=7, scales="free")+
        theme(axis.line = element_line(colour = "black"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_blank())

combined <- ggarrange(GL.plot, TG.plot, TyG.plot, TC.plot, HDL.plot, LDL.plot, TC.HDL.plot, ncol=1,
                      common.legend = TRUE, legend = "bottom")
GL.TGL.TyG_combined <- ggarrange(GL.plot, TG.plot, TyG.plot, ncol=1,
                      common.legend = TRUE, legend = "bottom")
#save at 7 x 15

Cholesterols_combined <- ggarrange(TC.plot, HDL.plot, LDL.plot, TC.HDL.plot, ncol=1,
                      common.legend = TRUE, legend = "bottom")
#save at 9 x 15
```

